# Configuration Pre-commit pour Arkalia-CIA
# Basée sur les standards des autres projets Arkalia

repos:
  # Black - Formatage automatique
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3.10
        args: [--line-length=88, --target-version=py310]

  # Ruff - Linting et imports
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  # MyPy - Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        additional_dependencies: [types-PyYAML, types-requests]
        args: [--ignore-missing-imports, --no-strict-optional]

  # Bandit - Sécurité
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args:
          [
            -r,
            arkalia_cia_python_backend/api.py,
            arkalia_cia_python_backend/database.py,
            arkalia_cia_python_backend/pdf_processor.py,
          ]

  # Safety - Vérification des vulnérabilités - temporairement désactivé
  # - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  #   rev: v1.3.2
  #   hooks:
  #     - id: python-safety-dependencies-check

  # Hooks généraux
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-docstring-first

  # Hooks spécifiques Python
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile, black, --line-length, "88"]

  # Hooks pour les fichiers de configuration - temporairement désactivé
  # - repo: https://github.com/adamchainz/blacken-docs
  #   rev: 1.16.0
  #   hooks:
  #     - id: blacken-docs
  #       additional_dependencies: [black==23.11.0]

# Configuration globale
default_stages: [pre-commit]
fail_fast: false
minimum_pre_commit_version: 3.0.0
