# Stub file for optional athalia_core.validation.security_validator module
from typing import Any

class CommandSecurityValidator:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def validate(self, command: str) -> bool: ...
    def run_comprehensive_scan(self, project_path: str) -> dict[str, Any]: ...
