# Stub file for optional athalia_core.metrics.collector module
from typing import Any

class MetricsCollector:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def collect(self) -> dict[str, Any]: ...
    def collect_all_metrics(self) -> dict[str, Any]: ...
