# Stub file for optional athalia_core.core.cache_manager module
from typing import Any

class CacheManager:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get(self, key: str) -> Any: ...
    def set(self, key: str, value: Any) -> None: ...
    def get_stats(self) -> dict[str, Any]: ...
